spring:
  application:
    name: Welcome-API

  boot:
    admin:
      client:
        url: http://localhost:9090
        instance:
          management-base-url: http://localhost:8080
        username: admin
        password: admin

management:
  endpoints:
    web:
      exposure:
        include: '*'  # Expose all management endpoints
  security:
    enabled: false  # Disable security for management endpoints
  basic:
    enabled: false  # Disable basic authentication for management endpoints

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/  # Eureka server URL for service discovery
